# Generated by Django 2.2.5 on 2019-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250, unique=True)),
                ('street_name', models.CharField(blank=True, max_length=250)),
                ('suburb', models.CharField(max_length=250)),
                ('postcode', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('contact_name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
